import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { io } from 'socket.io-client';
import { createApp } from '../server.js';

test('room authorization, capacity, turn ownership, reconnect, and QR', async t => {
  const server = createApp({ port: 3000 });
  await new Promise(resolve => server.http.listen(0, '127.0.0.1', resolve));
  const port = server.http.address().port; const base = `http://127.0.0.1:${port}`; const clients = [];
  t.after(() => { clients.forEach(c => c.disconnect()); server.close(); });
  const connect = async () => { const client = io(base, { transports: ['websocket'], forceNew: true }); clients.push(client); await new Promise(resolve => client.on('connect', resolve)); return client; };
  const send = (c, event, data = {}) => new Promise(resolve => c.emit(event, data, resolve));
  const shot = () => { const game = server.rooms.get(code).game; return { angle: 40, power: 40, weapon: game.shooter.weapon, turn: game.turn, shooterId: game.shooter.id }; };
  const host = await connect(), hostToken = randomUUID();
  const { code } = await send(host, 'create', { token: hostToken }); assert.match(code, /^[A-F0-9]{6}$/);
  const catalog = await fetch(`${base}/maps`).then(r => r.json()); assert.equal(catalog.length, 4);
  for (const map of catalog) { const preview = await fetch(`${base}/preview.json?map=${map.id}`).then(r => r.json()); assert.equal(preview.mapId, map.id); }
  assert.equal((await fetch(`${base}/preview.json?map=__proto__`)).status, 400);
  assert.ok((await send(host, 'selectMap', { mapId: '__proto__' })).error);
  assert.ok((await send(host, 'start', { mode: 'party' })).error);
  assert.ok((await send(host, 'start', { mode: 'practice' })).error);
  const bad = await connect(); assert.ok((await send(bad, 'resumeHost', { code, token: randomUUID() })).error);
  const players = [];
  for (let i = 0; i < 8; i++) {
    const c = await connect(), token = randomUUID();
    const result = await send(c, 'join', { code, token, name: `Player ${i}` }); assert.equal(result.id, c.id); players.push({ c, token });
  }
  assert.ok((await send(bad, 'join', { code, token: randomUUID(), name: 'Extra' })).error);
  assert.ok((await send(players[0].c, 'team', { team: 1 })).error);
  assert.ok((await send(players[0].c, 'start', { mode: 'party' })).error);
  assert.ok((await send(players[0].c, 'selectMap', { mapId: 'bridge' })).error);
  assert.ok((await send(host, 'selectMap', { mapId: 'bridge' })).ok);
  assert.ok((await send(host, 'start', { mode: 'party' })).ok);
  assert.equal(server.rooms.get(code).game.map.id, 'bridge');
  assert.ok((await send(host, 'selectMap', { mapId: 'tower' })).error);
  assert.ok((await send(players[1].c, 'fire', shot())).error);
  assert.ok((await send(players[0].c, 'fire', shot())).error);
  assert.ok((await send(players[0].c, 'readyAim')).ok);
  assert.ok((await send(players[0].c, 'aim', { ...shot(), angle: 'bad' })).error);
  assert.ok((await send(players[0].c, 'aim', { ...shot(), weapon: 'heavy' })).error);
  assert.ok((await send(players[0].c, 'fire', { ...shot(), shooterId: -1 })).error);
  assert.ok((await send(players[0].c, 'fire', { ...shot(), turn: 99 })).error);
  assert.ok((await send(players[0].c, 'fire', shot())).ok);
  const fired = server.rooms.get(code).game;
  const skill = fired.snapshot().activeSkill;
  assert.ok(skill?.available);
  assert.ok((await send(players[1].c, 'skill', { turn: fired.turn, shooterId: fired.firedShooterId, projectileId: skill.projectileId, action: skill.action })).error);
  assert.ok((await send(players[0].c, 'skill', { turn: fired.turn + 1, shooterId: fired.firedShooterId, projectileId: skill.projectileId, action: skill.action })).error);
  assert.ok((await send(players[0].c, 'skill', { turn: fired.turn, shooterId: fired.firedShooterId, projectileId: skill.projectileId, action: skill.action })).ok);
  assert.ok((await send(players[0].c, 'fire', shot())).error);
  assert.ok((await send(players[0].c, 'lobby')).error);
  const reconnectToken = players[0].token; players[0].c.disconnect();
  const replacement = await connect();
  assert.equal((await send(replacement, 'join', { code, token: reconnectToken })).id, replacement.id);
  assert.equal(server.rooms.get(code).players.length, 8);
  assert.equal(server.rooms.get(code).game.map.id, 'bridge');
  const qr = await fetch(`${base}/connection?room=${code}`).then(r => r.json()); assert.ok(qr.qr.startsWith('data:image/png;base64,')); assert.ok(qr.url.endsWith(`/?room=${code}`));
  assert.equal((await fetch(`${base}/connection?room=BAD`)).status, 404);
  assert.ok((await send(host, 'lobby')).ok); assert.equal(server.rooms.get(code).game, null);
  players[1].c.disconnect();
  await new Promise((resolve, reject) => {
    const deadline = Date.now() + 1000;
    const poll = () => server.rooms.get(code).players.length === 7 ? resolve() : Date.now() > deadline ? reject(new Error('Disconnected lobby player was not removed')) : setTimeout(poll, 10);
    poll();
  });
  const newcomer = await connect();
  assert.equal((await send(newcomer, 'join', { code, token: randomUUID() })).id, newcomer.id);
  assert.equal(server.rooms.get(code).players.length, 8);
  host.disconnect(); const resumed = await connect();
  assert.equal((await send(resumed, 'resumeHost', { code, token: hostToken })).code, code);
  assert.equal(server.rooms.get(code).mapId, 'bridge');
  assert.ok((await send(resumed, 'selectMap', { mapId: 'random' })).ok);
  assert.ok((await send(resumed, 'start', { mode: 'practice' })).ok);
  assert.ok(catalog.some(m => m.id === server.rooms.get(code).game.map.id));
  assert.ok((await send(resumed, 'fire', shot())).error);
  assert.ok((await send(replacement, 'fire', shot())).error);
  assert.ok((await send(replacement, 'readyAim')).ok);
  assert.ok((await send(replacement, 'fire', shot())).ok);
});
